// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:8bfa3991-34a3-4c6e-a04f-e4d1e225077d',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_U1MursQ0j',
    aws_user_pools_web_client_id: '6n4gp3t2sb3hih2j7romkf6u0b',
    oauth: {},
    aws_appsync_graphqlEndpoint: 'https://tf3fxm4r2nd6jjbamsdsywn2iq.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_user_files_s3_bucket: 'librarian-images-dev',
    aws_user_files_s3_bucket_region: 'us-east-1'
};

export default awsmobile;
